sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker

before_install:
  - chmod +x ./scripts/deploy.sh

install:
 - gradle build

after_success:
  - ./scripts/deploy.sh
